#pragma once
#ifndef SELFIE_DEFINITIONS_H
#define SELFIE_DEFINITIONS_H

#define TOPVIEW_ROWS 258
#define TOPVIEW_COLS 640

#define TOPVIEW_MIN_X 0.45
#define TOPVIEW_MAX_X 1.4
#define TOPVIEW_MIN_Y -1.3
#define TOPVIEW_MAX_Y 1.3

#endif  //  SELFIE_DEFINITIONS_H