detect_markings: 
  {
    threshold_c: -15,
    real_window_size: 0.1,

    pf_num_points: 3,
    pf_num_samples: 30,
    pf_num_samples_vis: 4,
    pf_std: 0.02,
    real_window_size: 0.05,
    threshold_c: -15,
    obstacle_window_size: 0.09,
    obstacles_threshold: 95
  }
detect_parking_spot: 
  {
    default_speed_in_parking_zone: 0.8,
    max_distance_to_free_place: 0.8,
    speed_when_found_place: 0.3,

    point_max_x: 2,
    point_max_y: 0.2,
    point_min_x: 0.01,
    point_min_y: -1
  }
extract_road_features: 
  {
    lookahead: 0.55,
    min_speed: 1.5,
    max_acceleration: 1.0,
    max_deceleration: 1.5,
    max_curvature: 1.8,
    average_window_size: 10
  }
free_drive: 
  {
    max_speed: 3.0,
    starting_line_distance_to_end: 0.45,
    intersection_distance_to_end: 0.8
  }
lane_controller:
  {
    right_lane_setpoint: -0.2,
    left_lane_setpoint: 0.2,

    maximum_speed: 2.0,
    safe_speed: 0.8,
    maximum_length_of_obstacle: 0.8,
    maximum_distance_to_obstacle: 0.5,
    safety_margin: 1.15,
    pos_tolerance: 0.01,
    num_proof_to_overtake: 3,
    num_corners_to_detect_: 3,

    ROI_min_x: 0.0,
    ROI_max_x: 0.9,
    ROI_min_y: -1.0,
    ROI_max_y: 1.0
  }
lidar: 
  {
    serial_port: "/dev/sensors/hokuyo_H1312790"
  }
offset_combiner: 
  {
    L: 0.3
  }
park_server: 
  {
    dist_turn: 0.17,
    idle_time: 2.0,
    max_rot: 0.8,
    max_turn: 0.8,
    minimal_start_parking_x_: -0.16,
    odom_to_back: -0.33,
    odom_to_front: 0.18,
    odom_to_laser: 0.0,
    parking_speed: 0.4
  }
pid_controller: 
  {
    Kd: 0.01,
    Ki: 0.0,
    Kp: 0.9,
    lower_limit: -0.785,
    upper_limit: 0.785,
    windup_limit: 10
  }
scheduler: 
  {
    begin_action: 1,
    parking_spot: 0.6,
    starting_distance: 1.0
  }
detect_obstacles: 
  {
    lidar_offset: 0.0,
    max_range: 2.0,
    min_range: 0.03,
    min_segment_size: 0.04,
    max_segment_size: 0.5,
    min_to_divide: 0.03,
    segment_threshold: 0.07,
    upside_down: false
  }
starting_procedure: 
  {
    starting_speed: 2.0
  }