detect_markings: 
  {
    threshold_c: -45,
    real_window_size: 0.1,

    pf_num_points: 3,
    pf_num_samples: 40,
    pf_num_samples_vis: 4,
    pf_std_min: 0.01,
    pf_std_max: 0.03,
    obstacle_window_size: 0.09,
    obstacles_threshold: 180,

    max_mid_line_distance: 0.12,
    max_mid_line_gap: 0.25
  }
detect_parking_spot: 
  {
    default_speed_in_parking_zone: 1.5,
    max_distance_to_free_place: 0.4,
    speed_when_found_place: 0.8,
    new_setpoint: -0.28,
    length_of_parking_area: 5.5,
    old_setpoint: -0.26,

    point_max_x: 2,
    point_max_y: 0.2,
    point_min_x: 0.01,
    point_min_y: -0.3
  }
extract_road_features: 
  {
    lookahead: 0.55,
    min_speed: 5.0,
    max_acceleration: 100.0,
    max_deceleration: 100.0,
    max_curvature: 1.8,
    average_window_size: 200
  }
free_drive: 
  {
    max_speed: 2.5,
    starting_line_distance_to_end: 0.65,
    intersection_distance_to_end: 1.3,
    distance_to_verify_event_: 1.0
  }
lane_controller:
  {
    right_lane_setpoint: -0.26,
    left_lane_setpoint: 0.19,

    ackermann_mode: true,

    maximum_speed: 2.2,
    slowdown_speed: 1.7,
    lane_change_speed: 1.2,
    lane_change_distance: 0.65,
    max_length_of_obstacle: 0.4,
    max_distance_to_obstacle: 1.2,
    safety_margin: 1.0,
    pos_tolerance: 0.01,
    num_proof_to_slowdown: 2,
    num_corners_to_detect: 2,
    lane_change_kp: 0.65,

    ROI_min_x: 0.5,
    ROI_max_x: 1.7,
    ROI_min_y: -1.0,
    ROI_max_y: 1.0,

    right_obst_area_min_x: 0.3,
    right_obst_area_max_x: 1.6,
    right_obst_area_min_y: -0.85,
    right_obst_area_max_y: 0.15,
  }
lidar: 
  {
    serial_port: "/dev/sensors/hokuyo_H1312790"
  }
offset_combiner: 
  {
    L: 0.25
  }
park_server: 
  {
    idle_time: 2.0,
    max_turn: 0.5,
    back_to_mid: 0.18,
    parking_speed: 0.8,
    start_parking_speed: 0.5,
    iter_distance: 0.09,
    angle_coeff: 0.54,
    turn_delay: 0.51,
    line_dist_end: 0.17
  }
intersection_server: 
  {
    distance_to_intersection: 0.75,
    road_width: 1.05,
    point_min_y: -0.5,
    point_max_y: 0.7,
    stop_time: 3,
    speed_default: 1.0,
    num_corners_to_detect: 1,
    distance_of_blind_approaching: 0.2,
  }
pid_controller: 
  {
    Kd: 0.12,
    Ki: 0.0,
    Kp: 1.0,
    lower_limit: -0.785,
    upper_limit: 0.785,
    windup_limit: 10
  }
scheduler: 
  {
    begin_action: 1,
    parking_spot: 0.63,
    parking_steering_mode: 1, # 0 - ackermann 1 - paralell
    drive_steering_mode: 2, # 0 - ackermann  1 - paralell 2 - front axis only 
    starting_distance: 1.0
  }
detect_obstacles: 
  {
    lidar_offset: 0.0,
    max_range: 2.0,
    min_range: 0.03,
    min_segment_size: 0.04,
    max_segment_size: 0.5,
    min_to_divide: 0.03,
    segment_threshold: 0.07,
    upside_down: false
  }
starting_procedure: 
  {
    starting_speed: 2.0,
    use_scan: false,
    use_qr: true,
    Kp: 1.00
  }
qr_decoder: 
  {
    min_detect_rate: 0.4,
    interations_to_vaild: 2
  }
stm32_bridge:
  {
    ackermann_offset_front: 0.0,
    ackermann_offset_back: 0.0,
    parallel_offset_front_right: 0.1,
    parallel_offset_back_right: 0.0,
    parallel_offset_front_left: 0.0,
    parallel_offset_back_left: -0.25,
    front_axis_offset: 0.0,
    back_axis_offset: 0.0
  }
diagnose: 
  {
    0_sensor_datatype: "LaserScan",
    0_sensor_directory: "/dev/sensors/hokuyo_H1312790",
    0_sensor_hz: 100,
    0_sensor_name: "Lidar",
    0_sensor_topic: "/scan",
    1_sensor_datatype: "Imu",
    1_sensor_hz: 250,
    1_sensor_name: "Imu",
    1_sensor_topic: "/imu",
    2_sensor_datatype: "Image",
    2_sensor_hz: 102,
    2_sensor_name: "Camera",
    2_sensor_topic: "/image_rect",
    3_sensor_datatype: "Float32",
    3_sensor_hz: 250,
    3_sensor_name: "STM",
    3_sensor_topic: "/stm32/speed",
    frequency: 2,
    debug: false,
    delay: 10
  }
