#goal definition
float32 min_spot_lenght #minimal length of parking spot
---
#result definition
geometry_msgs/Polygon parking_spot #4 points describing placement of parking spot
---
#feedback
uint32 action_status #one of enums describing state (see more on wiki)