#goal definition
float32 distance
---
#result definition

uint32 drive_mode #according to pressed button choose current mode
---

#feedback
uint32 action_status #one of enums describing state (see more on wiki)